# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

puts 'Cleaning database...'

Client.destroy_all
User.destroy_all
Appartement.destroy_all
Simulation.destroy_all


puts 'Creating users...'

User.create!(
  prenom: 'Michel',
  nom: 'Durand',
  email: 'michel.durand@cgp.com',
  password: 'password',
  carte_t: 'T01012019',
  image: 'https://res.cloudinary.com/agazielly/image/upload/v1567635152/William_Parry_zgpjfi.jpg')

User.create!(
  prenom: 'Jean',
  nom: 'Dupont',
  email: 'jean@dupont.com',
  password: 'password',
  carte_t: 'T12345678',
  image: 'https://res.cloudinary.com/agazielly/image/upload/v1567632683/Mamadou_Sylla_k9wvvq.jpg')

puts 'Finished creating users...'

puts 'Creating appartements...'

Appartement.create!(
    livraison: 'T4 2019',
    actabilite: 'actable',
    disponibilite: 'Disponible',
    prix: '350000',
    lot: 'N°209',
    etage: 'R+3',
    typologie: '3P',
    ville: 'Honfleur',
    adresse: '178 Chemin du Mont Bouis, La Riviere-Saint-Sauveur',
    nom_programme: 'Le Clos Saint-Germain',
    promoteur: 'Nexity',
    logo_promoteur: 'http:',
    image: 'https://res.cloudinary.com/agazielly/image/upload/v1567638893/Paris_appartement7_myex7l.jpg',
    departement: '75',
    loyer: '750',
    charges: '1010',
    scoring_prix: 2,
    scoring_rendement:3,
    scoring_potentiel:4,
    scoring_energie:4,
    scoring_qualite:3,
    scoring_amenagement:3,
    scoring_dynamisme:3,
    scoring_amenites:4,
    scoring_accessibilite:4,
    scoring_equipements:5,
    taxe_fonciere: '780'
    )

Appartement.create!(
    livraison: 'T1 2020',
    actabilite: 'actable',
    disponibilite: 'Indisponible',
    prix: '230000',
    lot: 'N°62',
    etage: 'R+5',
    typologie: '3P',
    ville: 'Paris',
    adresse: 'Porte de la Villette, Paris',
    nom_programme: 'Les ilots de Chaumont',
    promoteur: 'Cogedim',
    logo_promoteur: 'http:',
    image: 'https://res.cloudinary.com/agazielly/image/upload/v1567638890/Paris_appartement6_paudki.jpg',
    departement: '75',
    loyer: '680',
    charges: '810',
    scoring_prix: 2,
    scoring_rendement:3,
    scoring_potentiel:4,
    scoring_energie:4,
    scoring_qualite:3,
    scoring_amenagement:3,
    scoring_dynamisme:3,
    scoring_amenites:4,
    scoring_accessibilite:4,
    scoring_equipements:5,
    taxe_fonciere: '880'
    )

Appartement.create!(
    livraison: 'T2 2020',
    actabilite: 'non-actable',
    disponibilite: 'disponible',
    prix: '150000',
    lot: 'N°12',
    etage: 'R+2',
    typologie: '1P',
    ville: 'Pont-du-Casse',
    adresse: '519 Avenue de Cahors, Pont-du-Casse',
    nom_programme: "Fontaine d'Auteuil",
    promoteur: 'Kaufman & Broad',
    logo_promoteur: 'http:',
    image: 'https://res.cloudinary.com/agazielly/image/upload/v1567638898/Paris_appartement8_gwjhnu.jpg',
    departement: '75',
    loyer: '450',
    charges: '630',
    scoring_prix: 1,
    scoring_rendement:4,
    scoring_potentiel:2,
    scoring_energie:4,
    scoring_qualite:3,
    scoring_amenagement:3,
    scoring_dynamisme:3,
    scoring_amenites:4,
    scoring_accessibilite:4,
    scoring_equipements:5,
    taxe_fonciere: '780'
    )

Appartement.create!(
    livraison: 'T4 2019',
    actabilite: 'actable',
    disponibilite: 'Non-disponible',
    prix: '270000',
    lot: 'N°27',
    etage: 'R+2',
    typologie: '2P',
    ville: 'Boulogne',
    adresse: '86 Rue Gallieni, Boulogne',
    nom_programme: 'Carre Seine',
    promoteur: 'Bouygues Immmobilier',
    logo_promoteur: 'http:',
    image: 'https://res.cloudinary.com/agazielly/image/upload/v1567638898/Paris_appartement5_fmkcio.jpg',
    departement: '75',
    loyer: '510',
    charges: '680',
    scoring_prix: 4,
    scoring_rendement:5,
    scoring_potentiel:4,
    scoring_energie:4,
    scoring_qualite:3,
    scoring_amenagement:5,
    scoring_dynamisme:2,
    scoring_amenites:4,
    scoring_accessibilite:4,
    scoring_equipements:5,
    taxe_fonciere: '900'
    )

Appartement.create!(
    livraison: 'T3 2019',
    actabilite: 'actable',
    disponibilite: 'disponible',
    prix: '290000',
    lot: 'N°27',
    etage: 'R+2',
    typologie: '3P',
    ville: 'Nice',
    adresse: '85 Avenue Raoul Dufy, Nice',
    nom_programme: 'Le Domaine de Gairaut',
    promoteur: 'Cogedim',
    logo_promoteur: 'http:',
    image: 'https://res.cloudinary.com/agazielly/image/upload/v1567636290/Cogedim_Nice_Gairault_cspia8.jpg',
    departement: '06',
    loyer: '930',
    charges: '1460',
    scoring_prix: 3,
    scoring_rendement:3,
    scoring_potentiel:4,
    scoring_energie:4,
    scoring_qualite:3,
    scoring_amenagement:2,
    scoring_dynamisme:3,
    scoring_amenites:4,
    scoring_accessibilite:4,
    scoring_equipements:5,
    taxe_fonciere: '780'
    )

Appartement.create!(
    livraison: 'T2 2019',
    actabilite: 'actable',
    disponibilite: 'disponible',
    prix: '370000',
    lot: 'N°11',
    etage: 'R+3',
    typologie: '3P',
    ville: 'Nice',
    adresse: '88 Avenue Raoul Dufy, Nice',
    nom_programme: 'Corniche Marine',
    promoteur: 'Cogedim',
    logo_promoteur: 'http:',
    image: 'https://res.cloudinary.com/agazielly/image/upload/v1567636281/Corniche_Marine_kxk9yr.jpg',
    departement: '06',
    loyer: '1100',
    charges: '1600',
    scoring_prix: 3,
    scoring_rendement:3,
    scoring_potentiel:4,
    scoring_energie:4,
    scoring_qualite:3,
    scoring_amenagement:5,
    scoring_dynamisme:3,
    scoring_amenites:4,
    scoring_accessibilite:4,
    scoring_equipements:3,
    taxe_fonciere: '700'
    )

Appartement.create!(
    livraison: 'T2 2021',
    actabilite: 'actable',
    disponibilite: 'disponible',
    prix: '350000',
    lot: 'N°11',
    etage: 'R+3',
    typologie: '3P',
    ville: 'Nice',
    adresse: '3 ruelle Saint Roch, Nice',
    nom_programme: 'Carré Sérénice',
    promoteur: 'Cogedim',
    logo_promoteur: 'http:',
    image: 'https://res.cloudinary.com/agazielly/image/upload/v1567637184/Nice_Appartement_ndejds.jpg',
    departement: '06',
    loyer: '1050',
    charges: '1490',
    scoring_prix: 2,
    scoring_rendement:2,
    scoring_potentiel:3,
    scoring_energie:4,
    scoring_qualite:3,
    scoring_amenagement:4,
    scoring_dynamisme:3,
    scoring_amenites:4,
    scoring_accessibilite:4,
    scoring_equipements:4,
    taxe_fonciere: '780'
    )

Appartement.create!(
    livraison: 'T1 2022',
    actabilite: 'actable',
    disponibilite: 'disponible',
    prix: '262000',
    lot: 'N°13',
    etage: 'R+3',
    typologie: '2P',
    ville: 'Nice',
    adresse: '34 avenue des Diables Bleus, Nice',
    nom_programme: 'Nice Way',
    promoteur: 'Cogedim',
    logo_promoteur: 'http:',
    image: 'https://res.cloudinary.com/agazielly/image/upload/v1567636281/Cogedim_Nice_Way_emiji0.jpg',
    departement: '06',
    loyer: '880',
    charges: '1110',
    scoring_prix: 4,
    scoring_rendement:3,
    scoring_potentiel:4,
    scoring_energie:4,
    scoring_qualite:3,
    scoring_amenagement:5,
    scoring_dynamisme:3,
    scoring_amenites:4,
    scoring_accessibilite:4,
    scoring_equipements:5,
    taxe_fonciere: '580'
    )

Appartement.create!(
    livraison: 'T1 2022',
    actabilite: 'actable',
    disponibilite: 'non-disponible',
    prix: '281000',
    lot: 'N°7',
    etage: 'R+2',
    typologie: '3P',
    ville: 'Grasse',
    adresse: '15 chemin du Bois Fleuri, Grasse',
    nom_programme: 'Secret Park',
    promoteur: 'Cogedim',
    logo_promoteur: 'http:',
    image: 'https://res.cloudinary.com/agazielly/image/upload/v1567637183/Nice_Appartement3_v1xqop.jpg',
    departement: '06',
    loyer: '1000',
    charges: '1420',
    scoring_prix: 4,
    scoring_rendement:3,
    scoring_potentiel:4,
    scoring_energie:4,
    scoring_qualite:3,
    scoring_amenagement:2,
    scoring_dynamisme:3,
    scoring_amenites:4,
    scoring_accessibilite:4,
    scoring_equipements:1,
    taxe_fonciere: '780'
    )

Appartement.create!(
    livraison: 'T4 2019',
    actabilite: 'actable',
    disponibilite: 'disponible',
    prix: '286000',
    lot: 'N°5',
    etage: 'R+1',
    typologie: '3P',
    ville: 'Cannes',
    adresse: '152/154 Avenue Francis Tonner, Cannes',
    nom_programme: 'Villa Alice',
    promoteur: 'Cogedim',
    logo_promoteur: 'http:',
    image: 'https://res.cloudinary.com/agazielly/image/upload/v1567637180/Nice_Appartement2_n8yj7h.jpg',
    departement: '06',
    loyer: '985',
    charges: '1310',
    scoring_prix: 4,
    scoring_rendement:3,
    scoring_potentiel:4,
    scoring_energie:4,
    scoring_qualite:3,
    scoring_amenagement:5,
    scoring_dynamisme:4,
    scoring_amenites:4,
    scoring_accessibilite:4,
    scoring_equipements:5,
    taxe_fonciere: '790'
    )

Appartement.create!(
    livraison: 'T4 2022',
    actabilite: 'non-actable',
    disponibilite: 'non-disponible',
    prix: '286000',
    lot: 'N°5',
    etage: 'R+1',
    typologie: '3P',
    ville: 'Mougins',
    adresse: '539 avenue de Tournamy, Mougins',
    nom_programme: 'Cours des Arts',
    promoteur: 'Cogedim',
    logo_promoteur: 'http:',
    image: 'https://res.cloudinary.com/agazielly/image/upload/v1567637175/Nice_Appartement4_mtynxz.jpg',
    departement: '06',
    loyer: '880',
    charges: '1230',
    scoring_prix: 3,
    scoring_rendement:3,
    scoring_potentiel:4,
    scoring_energie:4,
    scoring_qualite:3,
    scoring_amenagement:2,
    scoring_dynamisme:3,
    scoring_amenites:4,
    scoring_accessibilite:4,
    scoring_equipements:5,
    taxe_fonciere: '480'
    )

Appartement.create!(
    livraison: 'T4 2022',
    actabilite: 'actable',
    disponibilite: 'disponible',
    prix: '185000',
    lot: 'N°9',
    etage: 'R+2',
    typologie: '1P',
    ville: 'Mougins',
    adresse: '489 Avenue de Tournamy, Mougins',
    nom_programme: 'Coeur Mougins',
    promoteur: 'Cogedim',
    logo_promoteur: 'http:',
    image: 'https://res.cloudinary.com/agazielly/image/upload/v1567637652/Mougins_Appartement1_a5ughn.jpg',
    departement: '06',
    loyer: '680',
    charges: '810',
    scoring_prix: 5,
    scoring_rendement:3,
    scoring_potentiel:4,
    scoring_energie:4,
    scoring_qualite:3,
    scoring_amenagement:5,
    scoring_dynamisme:2,
    scoring_amenites:4,
    scoring_accessibilite:4,
    scoring_equipements:5,
    taxe_fonciere: '780'
    )

Appartement.create!(
    livraison: 'T4 2022',
    actabilite: 'actable',
    disponibilite: 'disponible',
    prix: '216000',
    lot: 'N°13',
    etage: 'R+3',
    typologie: '2P',
    ville: 'Mougins',
    adresse: '489 Avenue de Tournamy, Mougins',
    nom_programme: 'Coeur Mougins',
    promoteur: 'Cogedim',
    logo_promoteur: 'http:',
    image: 'https://res.cloudinary.com/agazielly/image/upload/v1567637640/Mougins_Appartement5_fagftt.jpg',
    departement: '06',
    loyer: '760',
    charges: '1050',
    scoring_prix: 4,
    scoring_rendement:3,
    scoring_potentiel:4,
    scoring_energie:4,
    scoring_qualite:3,
    scoring_amenagement:5,
    scoring_dynamisme:3,
    scoring_amenites:4,
    scoring_accessibilite:4,
    scoring_equipements:5,
    taxe_fonciere: '950'
    )

Appartement.create!(
    livraison: 'T4 2022',
    actabilite: 'actable',
    disponibilite: 'disponible',
    prix: '301000',
    lot: 'N°14',
    etage: 'R+4',
    typologie: '3P',
    ville: 'Mougins',
    adresse: '489 Avenue de Tournamy, Mougins',
    nom_programme: 'Coeur Mougins',
    promoteur: 'Cogedim',
    logo_promoteur: 'http:',
    image: 'https://res.cloudinary.com/agazielly/image/upload/v1567637625/Mougins_Appartement2_fmurhm.jpg',
    departement: '06',
    loyer: '1140',
    charges: '1700',
    scoring_prix: 3,
    scoring_rendement:3,
    scoring_potentiel:3,
    scoring_energie:4,
    scoring_qualite:3,
    scoring_amenagement:5,
    scoring_dynamisme:3,
    scoring_amenites:4,
    scoring_accessibilite:4,
    scoring_equipements:5,
    taxe_fonciere: '780'
    )

Appartement.create!(
    livraison: 'T4 2020',
    actabilite: 'actable',
    disponibilite: 'disponible',
    prix: '685000',
    lot: 'N°11',
    etage: 'R+3',
    typologie: '3P',
    ville: 'Nantes',
    adresse: '25 rue de la Cour Bastille, Nantes',
    nom_programme: 'Cour Bastille',
    promoteur: 'Nexity',
    logo_promoteur: 'http:',
    image: 'https://res.cloudinary.com/agazielly/image/upload/v1567637184/Nice_Appartement_ndejds.jpg',
    departement: '44',
    loyer: '2400',
    charges: '3600',
    scoring_prix: 1,
    scoring_rendement:2,
    scoring_potentiel:2,
    scoring_energie:4,
    scoring_qualite:3,
    scoring_amenagement:5,
    scoring_dynamisme:3,
    scoring_amenites:4,
    scoring_accessibilite:4,
    scoring_equipements:5,
    taxe_fonciere: '1010'
    )

Appartement.create!(
    livraison: 'T4 2020',
    actabilite: 'actable',
    disponibilite: 'disponible',
    prix: '175000',
    lot: 'N°17',
    etage: 'R+1',
    typologie: '2P',
    ville: 'Coueron',
    adresse: '35 rue Jean Jaures, Coueron',
    nom_programme: 'Les Allees de la Bretèche',
    promoteur: 'Nexity',
    logo_promoteur: 'http:',
    image: 'https://res.cloudinary.com/agazielly/image/upload/v1567636290/Cogedim_Nice_Gairault_cspia8.jpg',
    departement: '44',
    loyer: '530',
    charges: '750',
    scoring_prix: 2,
    scoring_rendement:3,
    scoring_potentiel:4,
    scoring_energie:4,
    scoring_qualite:3,
    scoring_amenagement:2,
    scoring_dynamisme:3,
    scoring_amenites:4,
    scoring_accessibilite:4,
    scoring_equipements:2,
    taxe_fonciere: '780'
    )

Appartement.create!(
    livraison: 'T4 2020',
    actabilite: 'non-actable',
    disponibilite: 'disponible',
    prix: '273000',
    lot: 'N°7',
    etage: 'R+3',
    typologie: '2P',
    ville: 'Lyon',
    adresse: '8 rue Pierre Valdo, Lyon',
    nom_programme: 'Ivory Park',
    promoteur: 'Nexity',
    logo_promoteur: 'http:',
    image: 'https://res.cloudinary.com/agazielly/image/upload/v1567636281/Cogedim_Nice_Way_emiji0.jpg',
    departement: '69',
    loyer: '1300',
    charges: '1740',
    scoring_prix: 5,
    scoring_rendement:3,
    scoring_potentiel:5,
    scoring_energie:4,
    scoring_qualite:3,
    scoring_amenagement:5,
    scoring_dynamisme:4,
    scoring_amenites:4,
    scoring_accessibilite:4,
    scoring_equipements:5,
    taxe_fonciere: '730'
    )

Appartement.create!(
    livraison: 'T4 2020',
    actabilite: 'actable',
    disponibilite: 'disponible',
    prix: '357000',
    lot: 'N°10',
    etage: 'R+4',
    typologie: '3P',
    ville: 'Lyon',
    adresse: '28 rue Pierre Valdo, Lyon',
    nom_programme: 'Factory Link',
    promoteur: 'Nexity',
    logo_promoteur: 'http:',
    image: 'https://res.cloudinary.com/agazielly/image/upload/v1567636281/Corniche_Marine_kxk9yr.jpg',
    departement: '69',
    loyer: '1600',
    charges: '2800',
    scoring_prix: 2,
    scoring_rendement:2,
    scoring_potentiel:2,
    scoring_energie:4,
    scoring_qualite:3,
    scoring_amenagement:2,
    scoring_dynamisme:3,
    scoring_amenites:4,
    scoring_accessibilite:4,
    scoring_equipements:2,
    taxe_fonciere: '780'
    )

Appartement.create!(
   livraison: 'T4 2019',
   actabilite: 'actable',
   disponibilite: 'disponible',
   prix: '420000',
   lot: 'N°10',
   etage: 'R+4',
   typologie: '2P',
   ville: 'Cannes',
   adresse: 'rue d\'Antibes, Cannes',
   nom_programme: 'Factory Link',
   promoteur: 'Nexity',
   logo_promoteur: 'http:',
   image: 'https://res.cloudinary.com/agazielly/image/upload/v1567638395/Cannes_Appartement2_t4ku9i.jpg',
   departement: '06',
   loyer: '1820',
    charges: '2680',
    scoring_prix: 4,
    scoring_rendement:3,
    scoring_potentiel:4,
    scoring_energie:4,
    scoring_qualite:3,
    scoring_amenagement:5,
    scoring_dynamisme:3,
    scoring_amenites:4,
    scoring_accessibilite:4,
    scoring_equipements:5,
    taxe_fonciere: '380'
   )
Appartement.create!(
   livraison: 'T4 2019',
   actabilite: 'actable',
   disponibilite: 'disponible',
   prix: '1200000',
   lot: 'N°10',
   etage: 'R+4',
   typologie: '3P',
   ville: 'Cannes',
   adresse: 'la Croisette, Cannes',
   nom_programme: 'Factory Link',
   promoteur: 'Nexity',
   logo_promoteur: 'http:',
   image: 'https://res.cloudinary.com/agazielly/image/upload/v1567638395/Cannes_Maison1_br1esa.jpg',
   departement: '06',
   loyer: '3800',
    charges: '5620',
    scoring_prix: 4,
    scoring_rendement:3,
    scoring_potentiel:4,
    scoring_energie:4,
    scoring_qualite:3,
    scoring_amenagement:5,
    scoring_dynamisme:3,
    scoring_amenites:4,
    scoring_accessibilite:4,
    scoring_equipements:4,
    taxe_fonciere: '780'
   )
Appartement.create!(
   livraison: 'T4 2019',
   actabilite: 'actable',
   disponibilite: 'disponible',
   prix: '192000',
   lot: 'N°10',
   etage: 'R+4',
   typologie: '3P',
   ville: 'Cannes',
   adresse: 'la Croisette, Cannes',
   nom_programme: 'Factory Link',
   promoteur: 'Nexity',
   logo_promoteur: 'http:',
   image: 'https://res.cloudinary.com/agazielly/image/upload/v1567638395/Cannes_Appartement3_azg3ag.jpg',
   departement: '06',
   loyer: '3500',
    charges: '4700',
    scoring_prix: 4,
    scoring_rendement:3,
    scoring_potentiel:4,
    scoring_energie:4,
    scoring_qualite:3,
    scoring_amenagement:2,
    scoring_dynamisme:3,
    scoring_amenites:4,
    scoring_accessibilite:4,
    scoring_equipements:5,
    taxe_fonciere: '610'
   )
Appartement.create!(
   livraison: 'T4 2019',
   actabilite: 'actable',
   disponibilite: 'disponible',
   prix: '3200000',
   lot: 'N°10',
   etage: 'R+4',
   typologie: '3P',
   ville: 'Cannes',
   adresse: '78 Avenue Francis Tonner, Cannes',
   nom_programme: 'Factory Link',
   promoteur: 'Nexity',
   logo_promoteur: 'http:',
   image: 'https://res.cloudinary.com/agazielly/image/upload/v1567638394/Cannes_Appartement1_iqm3jt.jpg',
   departement: '06',
   loyer: '1200',
    charges: '1620',
    scoring_prix: 4,
    scoring_rendement:3,
    scoring_potentiel:4,
    scoring_energie:4,
    scoring_qualite:3,
    scoring_amenagement:3,
    scoring_dynamisme:3,
    scoring_amenites:4,
    scoring_accessibilite:4,
    scoring_equipements:4,
    taxe_fonciere: '780'
   )
Appartement.create!(
   livraison: 'T4 2019',
   actabilite: 'actable',
   disponibilite: 'disponible',
   prix: '3200000',
   lot: 'N°10',
   etage: 'R+4',
   typologie: '3P',
   ville: 'Cannes',
   adresse: '26 Avenue de Lattre de Tassigny, Cannes',
   nom_programme: 'Factory Link',
   promoteur: 'Nexity',
   logo_promoteur: 'http:',
   image: 'https://res.cloudinary.com/agazielly/image/upload/v1567637183/Nice_Appartement3_v1xqop.jpg',
   departement: '06',
   loyer: '1500',
    charges: '2240',
    scoring_prix: 4,
    scoring_rendement:3,
    scoring_potentiel:4,
    scoring_energie:4,
    scoring_qualite:2,
    scoring_amenagement:3,
    scoring_dynamisme:3,
    scoring_amenites:4,
    scoring_accessibilite:4,
    scoring_equipements:2,
    taxe_fonciere: '800'
   )
Appartement.create!(
   livraison: 'T4 2019',
   actabilite: 'actable',
   disponibilite: 'disponible',
   prix: '505094',
   lot: 'N°10',
   etage: 'R+4',
   typologie: '2P',
   ville: 'Cannes',
   adresse: '2 Boulevard Delaup, Cannes',
   nom_programme: 'Factory Link',
   promoteur: 'Nexity',
   logo_promoteur: 'http:',
   image: 'https://res.cloudinary.com/agazielly/image/upload/v1567638394/Cannes_Appartement1_iqm3jt.jpg',
   departement: '06',
   loyer: '2000',
    charges: '3000',
    scoring_prix: 5,
    scoring_rendement:4,
    scoring_potentiel:4,
    scoring_energie:4,
    scoring_qualite:5,
    scoring_amenagement:5,
    scoring_dynamisme:4,
    scoring_amenites:4,
    scoring_accessibilite:4,
    scoring_equipements:4,
    taxe_fonciere: '780'
   )
Appartement.create!(
   livraison: 'T4 2019',
   actabilite: 'actable',
   disponibilite: 'disponible',
   prix: '395093',
   lot: 'N°10',
   etage: 'R+4',
   typologie: '3P',
   ville: 'Cannes',
   adresse: '7 Avenue Pierre Semard, Cannes',
   nom_programme: 'Factory Link',
   promoteur: 'Nexity',
   logo_promoteur: 'http:',
   image: 'https://res.cloudinary.com/agazielly/image/upload/v1567638897/Paris_appartement3_dxm0fo.jpg',
   departement: '06',
   loyer: '1800',
    charges: '2800',
    scoring_prix: 4,
    scoring_rendement:3,
    scoring_potentiel:3,
    scoring_energie:4,
    scoring_qualite:3,
    scoring_amenagement:4,
    scoring_dynamisme:3,
    scoring_amenites:4,
    scoring_accessibilite:4,
    scoring_equipements:4,
    taxe_fonciere: '1280'
   )
Appartement.create!(
   livraison: 'T4 2019',
   actabilite: 'actable',
   disponibilite: 'disponible',
   prix: '723393',
   lot: 'N°10',
   etage: 'R+4',
   typologie: '3P',
   ville: 'Cannes',
   adresse: '4 Avenue Andre Capron, Cannes',
   nom_programme: 'Factory Link',
   promoteur: 'Nexity',
   logo_promoteur: 'http:',
   image: 'https://res.cloudinary.com/agazielly/image/upload/v1567638896/Paris_appartement1_gupjyx.jpg',
   departement: '06',
   loyer: '2600',
   charges: '3840',
   scoring_prix: 4,
   scoring_rendement:3,
   scoring_potentiel:4,
   scoring_energie:4,
   scoring_qualite:3,
   scoring_amenagement:4,
   scoring_dynamisme:3,
   scoring_amenites:4,
   scoring_accessibilite:4,
   scoring_equipements:5,
    taxe_fonciere: '780'
   )
Appartement.create!(
   livraison: 'T4 2019',
   actabilite: 'actable',
   disponibilite: 'disponible',
   prix: '602393',
   lot: 'N°10',
   etage: 'R+4',
   typologie: '3P',
   ville: 'Cannes',
   adresse: '111 Rue Antibes, Cannes',
   nom_programme: 'Factory Link',
   promoteur: 'Nexity',
   logo_promoteur: 'http:',
   image: 'https://res.cloudinary.com/agazielly/image/upload/v1567638896/Paris_appartement2_onx0uu.jpg',
   departement: '06',
   loyer: '2500',
   charges: '3700',
   scoring_prix: 4,
   scoring_rendement:3,
   scoring_potentiel:4,
   scoring_energie:4,
   scoring_qualite:2,
   scoring_amenagement:3,
   scoring_dynamisme:3,
   scoring_amenites:4,
   scoring_accessibilite:2,
   scoring_equipements:5,
    taxe_fonciere: '480'
   )
Appartement.create!(
   livraison: 'T4 2019',
   actabilite: 'actable',
   disponibilite: 'disponible',
   prix: '302393',
   lot: 'N°10',
   etage: 'R+4',
   typologie: '2P',
   ville: 'Cannes',
   adresse: '18 Rue des Freres Pradignac, Cannes',
   nom_programme: 'Factory Link',
   promoteur: 'Nexity',
   logo_promoteur: 'http:',
   image: 'https://res.cloudinary.com/agazielly/image/upload/v1567638894/Paris_appartement4_avvbj7.jpg',
   departement: '06',
   loyer: '1120',
   charges: '1830',
   scoring_prix: 4,
   scoring_rendement:4,
   scoring_potentiel:4,
   scoring_energie:4,
   scoring_qualite:3,
   scoring_amenagement:3,
   scoring_dynamisme:3,
   scoring_amenites:4,
   scoring_accessibilite:4,
   scoring_equipements:5,
    taxe_fonciere: '780'
   )


Appartement.create!(
    livraison: 'T4 2019',
    actabilite: 'actable',
    disponibilite: 'Disponible',
    prix: '350000',
    lot: 'N°209',
    etage: 'R+3',
    typologie: '2P',
    ville: 'Nice',
    adresse: '2 Avenue Auguste Verola, Nice',
    nom_programme: 'Maison Neuve',
    promoteur: 'Nexity',
    logo_promoteur: 'http:',
    image: 'https://res.cloudinary.com/agazielly/image/upload/v1567638893/Paris_appartement7_myex7l.jpg',
    departement: '06',
    loyer: '1130',
    charges: '1740',
    scoring_prix: 4,
    scoring_rendement:3,
    scoring_potentiel:4,
    scoring_energie:4,
    scoring_qualite:3,
    scoring_amenagement:5,
    scoring_dynamisme:3,
    scoring_amenites:4,
    scoring_accessibilite:4,
    scoring_equipements:5,
    taxe_fonciere: '730'
    )

Appartement.create!(
    livraison: 'T1 2020',
    actabilite: 'actable',
    disponibilite: 'Indisponible',
    prix: '220000',
    lot: 'N°62',
    etage: 'R+5',
    typologie: '3P',
    ville: 'Paris',
    adresse: 'Porte de Saint Honore, Paris',
    nom_programme: 'Les ilots du Pont de Seine',
    promoteur: 'Cogedim',
    logo_promoteur: 'http:',
    image: 'https://res.cloudinary.com/agazielly/image/upload/v1567638890/Paris_appartement6_paudki.jpg',
    departement: '06',
    loyer: '820',
    charges: '1230',
    scoring_prix: 2,
    scoring_rendement:3,
    scoring_potentiel:2,
    scoring_energie:4,
    scoring_qualite:3,
    scoring_amenagement:4,
    scoring_dynamisme:3,
    scoring_amenites:4,
    scoring_accessibilite:4,
    scoring_equipements:3,
    taxe_fonciere: '1080'
    )

Appartement.create!(
    livraison: 'T4 2019',
    actabilite: 'non-actable',
    disponibilite: 'disponible',
    prix: '150000',
    lot: 'N°12',
    etage: 'R+2',
    typologie: '1P',
    ville: 'Pont-du-Casse',
    adresse: '519 Avenue de Cahors, Pont-du-Casse',
    nom_programme: "Fontaine d'Auteuil",
    promoteur: 'Kaufman & Broad',
    logo_promoteur: 'http:',
    image: 'https://res.cloudinary.com/agazielly/image/upload/v1567638394/Cannes_Appartement1_iqm3jt.jpg',
    departement: '06',
    loyer: '480',
    charges: '780',
    scoring_prix: 4,
    scoring_rendement:3,
    scoring_potentiel:4,
    scoring_energie:4,
    scoring_qualite:3,
    scoring_amenagement:5,
    scoring_dynamisme:3,
    scoring_amenites:4,
    scoring_accessibilite:4,
    scoring_equipements:5,
    taxe_fonciere: '780'
    )

Appartement.create!(
    livraison: 'T4 2019',
    actabilite: 'actable',
    disponibilite: 'Non-disponible',
    prix: '270000',
    lot: 'N°27',
    etage: 'R+2',
    typologie: '2P',
    ville: 'Boulogne',
    adresse: '86 Rue Gallieni, Boulogne',
    nom_programme: 'Carre Seine',
    promoteur: 'Bouygues Immmobilier',
    logo_promoteur: 'http:',
    image: 'https://res.cloudinary.com/agazielly/image/upload/v1567637625/Mougins_Appartement2_fmurhm.jpg',
    departement: '06',
    loyer: '980',
    charges: '1430',
    scoring_prix: 3,
    scoring_rendement:3,
    scoring_potentiel:4,
    scoring_energie:4,
    scoring_qualite:3,
    scoring_amenagement:4,
    scoring_dynamisme:3,
    scoring_amenites:4,
    scoring_accessibilite:4,
    scoring_equipements:5,
    taxe_fonciere: '780'
    )

Appartement.create!(
    livraison: 'T4 2019',
    actabilite: 'actable',
    disponibilite: 'disponible',
    prix: '290000',
    lot: 'N°27',
    etage: 'R+2',
    typologie: '3P',
    ville: 'Nice',
    adresse: '9 ruelle Saint Roch, Nice',
    nom_programme: 'Le Domaine de Gairaut',
    promoteur: 'Cogedim',
    logo_promoteur: 'http:',
    image: 'https://res.cloudinary.com/agazielly/image/upload/v1567637183/Nice_Appartement3_v1xqop.jpg',
    departement: '06',
    loyer: '1170',
    charges: '1640',
    scoring_prix: 5,
    scoring_rendement:4,
    scoring_potentiel:4,
    scoring_energie:4,
    scoring_qualite:3,
    scoring_amenagement:3,
    scoring_dynamisme:4,
    scoring_amenites:4,
    scoring_accessibilite:4,
    scoring_equipements:5,
    taxe_fonciere: '600'
    )

Appartement.create!(
    livraison: 'T4 2019',
    actabilite: 'actable',
    disponibilite: 'disponible',
    prix: '370000',
    lot: 'N°11',
    etage: 'R+3',
    typologie: '3P',
    ville: 'Nice',
    adresse: '88 Avenue Raoul Dufy, Nice',
    nom_programme: 'Corniche Marine',
    promoteur: 'Cogedim',
    logo_promoteur: 'http:',
    image: 'https://res.cloudinary.com/agazielly/image/upload/v1567636281/Corniche_Marine_kxk9yr.jpg',
    departement: '06',
    loyer: '1460',
    charges: '2230',
    scoring_prix: 4,
    scoring_rendement:3,
    scoring_potentiel:4,
    scoring_energie:4,
    scoring_qualite:3,
    scoring_amenagement:5,
    scoring_dynamisme:3,
    scoring_amenites:4,
    scoring_accessibilite:4,
    scoring_equipements:5,
    taxe_fonciere: '780'
    )

Appartement.create!(
    livraison: 'T4 2019',
    actabilite: 'actable',
    disponibilite: 'disponible',
    prix: '350000',
    lot: 'N°11',
    etage: 'R+3',
    typologie: '3P',
    ville: 'Nice',
    adresse: '3 ruelle Saint Roch, Nice',
    nom_programme: 'Carre Serenice',
    promoteur: 'Cogedim',
    logo_promoteur: 'http:',
    image: 'https://res.cloudinary.com/agazielly/image/upload/v1567636281/Cogedim_Nice_Way_emiji0.jpg',
    departement: '06',
    loyer: '1150',
    charges: '1760',
    scoring_prix: 3,
    scoring_rendement:3,
    scoring_potentiel:3,
    scoring_energie:4,
    scoring_qualite:3,
    scoring_amenagement:4,
    scoring_dynamisme:4,
    scoring_amenites:4,
    scoring_accessibilite:4,
    scoring_equipements:3,
    taxe_fonciere: '785'
    )

Appartement.create!(
    livraison: 'T4 2019',
    actabilite: 'actable',
    disponibilite: 'disponible',
    prix: '262000',
    lot: 'N°13',
    etage: 'R+3',
    typologie: '2P',
    ville: 'Nice',
    adresse: '125 Prom. des Anglais, Nice',
    nom_programme: 'Nice Way',
    promoteur: 'Cogedim',
    logo_promoteur: 'http:',
    image: 'https://res.cloudinary.com/agazielly/image/upload/v1567638395/Cannes_Appartement3_azg3ag.jpg',
    departement: '06',
    loyer: '880',
    charges: '1220',
    scoring_prix: 4,
    scoring_rendement:3,
    scoring_potentiel:4,
    scoring_energie:4,
    scoring_qualite:3,
    scoring_amenagement:5,
    scoring_dynamisme:3,
    scoring_amenites:4,
    scoring_accessibilite:4,
    scoring_equipements:5,
    taxe_fonciere: '900'
    )

Appartement.create!(
    livraison: 'T4 2019',
    actabilite: 'actable',
    disponibilite: 'non-disponible',
    prix: '281000',
    lot: 'N°7',
    etage: 'R+2',
    typologie: '3P',
    ville: 'Nice',
    adresse: '4 Rue Bonaparte, Nice',
    nom_programme: 'Secret Park',
    promoteur: 'Cogedim',
    logo_promoteur: 'http:',
    image: 'https://res.cloudinary.com/agazielly/image/upload/v1567636290/Cogedim_Nice_Gairault_cspia8.jpg',
    departement: '06',
    loyer: '1120',
    charges: '2000',
    scoring_prix: 4,
    scoring_rendement:3,
    scoring_potentiel:4,
    scoring_energie:4,
    scoring_qualite:3,
    scoring_amenagement:5,
    scoring_dynamisme:3,
    scoring_amenites:4,
    scoring_accessibilite:4,
    scoring_equipements:5,
    taxe_fonciere: '780'
    )

Appartement.create!(
    livraison: 'T4 2019',
    actabilite: 'actable',
    disponibilite: 'disponible',
    prix: '286000',
    lot: 'N°5',
    etage: 'R+1',
    typologie: '3P',
    ville: 'Nice',
    adresse: '152/154 Avenue Francis Tonner, Nice',
    nom_programme: 'Villa Alice',
    promoteur: 'Cogedim',
    logo_promoteur: 'http:',
    image: 'https://res.cloudinary.com/agazielly/image/upload/v1567638395/Cannes_Appartement3_azg3ag.jpg',
    departement: '06',
    loyer: '1120',
    charges: '1920',
    scoring_prix: 4,
    scoring_rendement:5,
    scoring_potentiel:4,
    scoring_energie:4,
    scoring_qualite:3,
    scoring_amenagement:5,
    scoring_dynamisme:3,
    scoring_amenites:2,
    scoring_accessibilite:4,
    scoring_equipements:4,
    taxe_fonciere: '450'
    )

Appartement.create!(
    livraison: 'T4 2019',
    actabilite: 'non-actable',
    disponibilite: 'non-disponible',
    prix: '286000',
    lot: 'N°5',
    etage: 'R+1',
    typologie: '3P',
    ville: 'Nice',
    adresse: '26 Avenue Malaussena, Nice',
    nom_programme: 'Cours des Arts',
    promoteur: 'Cogedim',
    logo_promoteur: 'http:',
    image: 'https://res.cloudinary.com/agazielly/image/upload/v1567636281/Corniche_Marine_kxk9yr.jpg',
    departement: '06',
    loyer: '1120',
    charges: '1920',
    scoring_prix: 4,
    scoring_rendement:2,
    scoring_potentiel:4,
    scoring_energie:4,
    scoring_qualite:3,
    scoring_amenagement:3,
    scoring_dynamisme:3,
    scoring_amenites:4,
    scoring_accessibilite:4,
    scoring_equipements:4,
    taxe_fonciere: '780'
    )

Appartement.create!(
    livraison: 'T4 2019',
    actabilite: 'actable',
    disponibilite: 'disponible',
    prix: '185000',
    lot: 'N°9',
    etage: 'R+2',
    typologie: '3P',
    ville: 'Nice',
    adresse: '8 Rue Rossini, Nice',
    nom_programme: 'Coeur Mougins',
    promoteur: 'Cogedim',
    logo_promoteur: 'http:',
    image: 'https://res.cloudinary.com/agazielly/image/upload/v1567638894/Paris_appartement4_avvbj7.jpg',
    departement: '06',
    loyer: '820',
    charges: '1300',
    scoring_prix: 3,
    scoring_rendement:3,
    scoring_potentiel:2,
    scoring_energie:3,
    scoring_qualite:4,
    scoring_amenagement:3,
    scoring_dynamisme:3,
    scoring_amenites:4,
    scoring_accessibilite:3,
    scoring_equipements:4,
    taxe_fonciere: '780'
    )

Appartement.create!(
    livraison: 'T4 2019',
    actabilite: 'actable',
    disponibilite: 'disponible',
    prix: '216000',
    lot: 'N°13',
    etage: 'R+3',
    typologie: '2P',
    ville: 'Nice',
    adresse: '81, Rue de France, Nice',
    nom_programme: 'Coeur Mougins',
    promoteur: 'Cogedim',
    logo_promoteur: 'http:',
    image: 'https://res.cloudinary.com/agazielly/image/upload/v1567638896/Paris_appartement1_gupjyx.jpg',
    departement: '06',
    loyer: '920',
    charges: '1200',
    scoring_prix: 4,
    scoring_rendement:3,
    scoring_potentiel:4,
    scoring_energie:4,
    scoring_qualite:3,
    scoring_amenagement:5,
    scoring_dynamisme:3,
    scoring_amenites:4,
    scoring_accessibilite:4,
    scoring_equipements:5,
    taxe_fonciere: '850'
    )


Appartement.create!(
    livraison: 'T4 2019',
    actabilite: 'actable',
    disponibilite: 'disponible',
    prix: '301000',
    lot: 'N°14',
    etage: 'R+4',
    typologie: '3P',
    ville: 'Nice',
    adresse: '4 Rue Bonaparte, Nice',
    nom_programme: 'Coeur Mougins',
    promoteur: 'Cogedim',
    logo_promoteur: 'http:',
    image: 'https://res.cloudinary.com/agazielly/image/upload/v1567638394/Cannes_Appartement1_iqm3jt.jpg',
    departement: '06',
    scoring_prix: 2,
    scoring_rendement:3,
    scoring_potentiel:3,
    scoring_energie:4,
    scoring_qualite:4,
    scoring_amenagement:2,
    scoring_dynamisme:3,
    scoring_amenites:5,
    scoring_accessibilite:4,
    scoring_equipements:3,
    loyer: '1400',
    charges: '2300',
    taxe_fonciere: '780'
    )

Appartement.create!(
    livraison: 'T4 2019',
    actabilite: 'actable',
    disponibilite: 'disponible',
    prix: '685000',
    lot: 'N°11',
    etage: 'R+3',
    typologie: '3P',
    ville: 'Nice',
    adresse: '25 rue de la Cour Bastille, Nice',
    nom_programme: 'Cour Bastille',
    promoteur: 'Nexity',
    logo_promoteur: 'http:',
    image: 'https://res.cloudinary.com/agazielly/image/upload/v1567637175/Nice_Appartement4_mtynxz.jpg',
    departement: '06',
    scoring_prix: 2,
    scoring_rendement:3,
    scoring_potentiel:4,
    scoring_energie:4,
    scoring_qualite:3,
    scoring_amenagement:2,
    scoring_dynamisme:5,
    scoring_amenites:4,
    scoring_accessibilite:4,
    scoring_equipements:4,
    loyer: '2710',
    charges: '4000',
    taxe_fonciere: '860'
    )

Appartement.create!(
    livraison: 'T4 2019',
    actabilite: 'actable',
    disponibilite: 'disponible',
    prix: '106000',
    lot: 'N°17',
    etage: 'R+1',
    typologie: '2P',
    ville: 'Nice',
    adresse: '7 Prom. des Anglais, Nice',
    nom_programme: 'Les Allees de la Bretèche',
    promoteur: 'Nexity',
    logo_promoteur: 'http:',
    image: 'https://res.cloudinary.com/agazielly/image/upload/v1567638890/Paris_appartement6_paudki.jpg',
    departement: '06',
    scoring_prix: 5,
    scoring_rendement:4,
    scoring_potentiel:4,
    scoring_energie:4,
    scoring_qualite:4,
    scoring_amenagement:5,
    scoring_dynamisme:4,
    scoring_amenites:4,
    scoring_accessibilite:4,
    scoring_equipements:5,
    loyer: '380',
    charges: '640',
    taxe_fonciere: '780'
    )

Appartement.create!(
    livraison: 'T4 2019',
    actabilite: 'non-actable',
    disponibilite: 'disponible',
    prix: '273000',
    lot: 'N°7',
    etage: 'R+3',
    typologie: '2P',
    ville: 'Nice',
    adresse: '8 Rue Alphonse Karr, Nice',
    nom_programme: 'Ivory Park',
    promoteur: 'Nexity',
    logo_promoteur: 'http:',
    image: 'https://res.cloudinary.com/agazielly/image/upload/v1567638890/Paris_appartement6_paudki.jpg',
    departement: '06',
    scoring_prix: 2,
    scoring_rendement:3,
    scoring_potentiel:3,
    scoring_energie:4,
    scoring_qualite:4,
    scoring_amenagement:5,
    scoring_dynamisme:3,
    scoring_amenites:2,
    scoring_accessibilite:3,
    scoring_equipements:3,
    loyer: '820',
    charges: '1530',
    taxe_fonciere: '700'
    )

Appartement.create!(
    livraison: 'T4 2019',
    actabilite: 'actable',
    disponibilite: 'disponible',
    prix: '357000',
    lot: 'N°10',
    etage: 'R+4',
    typologie: '5P',
    ville: 'Nice',
    adresse: '27 av Georges Clemenceau, Nice',
    nom_programme: 'Factory Link',
    promoteur: 'Nexity',
    logo_promoteur: 'http:',
    image: 'https://res.cloudinary.com/agazielly/image/upload/v1567637625/Mougins_Appartement2_fmurhm.jpg',
    departement: '06',
    scoring_prix: 4,
    scoring_rendement:5,
    scoring_potentiel:4,
    scoring_energie:4,
    scoring_qualite:4,
    scoring_amenagement:5,
    scoring_dynamisme:3,
    scoring_amenites:1,
    scoring_accessibilite:4,
    scoring_equipements:2,
    loyer: '1240',
    charges: '1930',
    taxe_fonciere: '780'
    )

puts 'Love you mum'
puts 'Finished creating apartments...'

puts 'Creating clients...'

Client.create!(
    prenom: 'Alexandre',
    nom: 'Coulier',
    civilite: 'Monsieur',
    tmi: '30.O',
    user_id: User.all[0].id,
    statut_marital: 'Célibataire',
    parts_fiscales: '1',
    revenu_net_imposable: '70000.00',
    image: 'https://res.cloudinary.com/agazielly/image/upload/v1567632654/Alexandre_Coulier_fxrjvy.jpg'
    )

Client.create!(
    prenom: 'Marie-Caroline',
    nom: 'Meijer',
    civilite: 'Madame',
    tmi: '35.0',
    user_id: User.all[0].id,
    statut_marital: 'Mariée',
    parts_fiscales: 2,
    revenu_net_imposable: '80000.00',
    image: 'https://res.cloudinary.com/agazielly/image/upload/v1567632657/Marie-Caroline_Meijer_oux7ki.jpg'
    )

Client.create!(
    prenom: 'Axelle',
    nom: 'Bourneuf',
    civilite: 'Madame',
    tmi: '30.0',
    user_id: User.all[0].id,
    statut_marital: 'Mariée',
    parts_fiscales: 3,
    revenu_net_imposable: '75000.00',
    image: 'https://res.cloudinary.com/agazielly/image/upload/v1567632654/Axelle_Bourneuf2_fydujo.jpg'
    )

Client.create!(
    prenom: 'Lior',
    nom: 'Levy',
    civilite: 'Monsieur',
    tmi: '18.0',
    user_id: User.all[0].id,
    statut_marital: 'Célibataire',
    parts_fiscales: 1,
    revenu_net_imposable: '35000.00',
    image: 'https://res.cloudinary.com/agazielly/image/upload/v1567632657/Lior_Levy_n7hfme.jpg'
    )

Client.create!(
    prenom: 'Pauline',
    nom: 'Garnier',
    civilite: 'Mademoiselle',
    tmi: '18.0',
    user_id: User.all[0].id,
    statut_marital: 'Célibataire',
    parts_fiscales: 1,
    revenu_net_imposable: '35000.00',
    image: 'https://res.cloudinary.com/agazielly/image/upload/v1567632680/Pauline_Garnier_flffxf.jpg'
    )

Client.create!(
    prenom: 'Gaëtan',
    nom: 'Ok',
    civilite: 'Monsieur',
    tmi: '15.0',
    user_id: User.all[0].id,
    statut_marital: 'Célibataire',
    parts_fiscales: 1,
    revenu_net_imposable: '45000.00',
    image: 'https://res.cloudinary.com/agazielly/image/upload/v1567633948/Gaetan_Ok_pgpqkq.jpg'
    )

Client.create!(
    prenom: 'Hubert',
    nom: 'Kuoch',
    civilite: 'Monsieur',
    tmi: '40.0',
    user_id: User.all[0].id,
    statut_marital: 'Célibataire',
    parts_fiscales: 1,
    revenu_net_imposable: '115000.00',
    image: 'https://res.cloudinary.com/agazielly/image/upload/v1567632655/Hubert_Kuoch_d6ktr3.jpg'
    )

Client.create!(
    prenom: 'Alice',
    nom: 'Fabre',
    civilite: 'Madame',
    tmi: '25.0',
    user_id: User.all[0].id,
    statut_marital: 'Célibataire',
    parts_fiscales: 1,
    revenu_net_imposable: '55000.00',
    image: 'https://res.cloudinary.com/agazielly/image/upload/v1567632681/Alice_Fabre_c0hxve.jpg'
    )

puts 'Finished creating clients...'
sleep 2
puts 'Success is not final, failure is not fatal: it is the courage to continue that counts.'
